# Build stage
FROM golang:1.19-alpine3.16 AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go
COPY cfg.env .
COPY db/migration ./db/migration

EXPOSE 8080
ENV CGO_ENABLED=0

ENTRYPOINT ["/app/main" ]