version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=payments
  api:
    build:
      context: .
      dockerfile: Dockerfile.relese
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 100M
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/payments?sslmode=disable
      - TEST_DB_SOURCE=postgresql://root:secret@postgres:5432/payments_test?sslmode=disable
    depends_on:
      - postgres
